-- HAGAV Studio - estrutura inicial Supabase (comercial + rastreio de origem)
-- Executar no SQL Editor do Supabase (projeto de producao).

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  fluxo text not null default 'WhatsApp',
  pagina text not null default '',
  origem text not null default '',
  status text not null default 'novo',
  nome text not null default '',
  whatsapp text not null default '',
  observacoes text not null default ''
);

create table if not exists public.orcamentos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  fluxo text not null default '',
  pagina text not null default 'orcamento',
  origem text not null default 'hagav.com.br',
  status text not null default 'novo',
  nome text not null default '',
  whatsapp text not null default '',
  servico text not null default '',
  quantidade text not null default '',
  material_gravado text not null default '',
  tempo_bruto text not null default '',
  prazo text not null default '',
  referencia text not null default '',
  observacoes text not null default '',
  detalhes text not null default ''
);

create table if not exists public.contatos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  fluxo text not null default 'Contato',
  pagina text not null default '',
  origem text not null default '',
  status text not null default 'novo',
  nome text not null default '',
  whatsapp text not null default '',
  mensagem text not null default ''
);

create index if not exists idx_leads_created_at on public.leads (created_at desc);
create index if not exists idx_leads_fluxo on public.leads (fluxo);
create index if not exists idx_leads_origem on public.leads (origem);
create index if not exists idx_leads_status on public.leads (status);

create index if not exists idx_orcamentos_created_at on public.orcamentos (created_at desc);
create index if not exists idx_orcamentos_fluxo on public.orcamentos (fluxo);
create index if not exists idx_orcamentos_origem on public.orcamentos (origem);
create index if not exists idx_orcamentos_status on public.orcamentos (status);
create index if not exists idx_orcamentos_whatsapp on public.orcamentos (whatsapp);

create index if not exists idx_contatos_created_at on public.contatos (created_at desc);
create index if not exists idx_contatos_status on public.contatos (status);

alter table public.leads enable row level security;
alter table public.orcamentos enable row level security;
alter table public.contatos enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'leads_status_check'
  ) then
    alter table public.leads
      add constraint leads_status_check
      check (status in ('novo', 'chamado', 'proposta enviada', 'fechado', 'perdido'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orcamentos_status_check'
  ) then
    alter table public.orcamentos
      add constraint orcamentos_status_check
      check (status in ('novo', 'chamado', 'proposta enviada', 'fechado', 'perdido'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'contatos_status_check'
  ) then
    alter table public.contatos
      add constraint contatos_status_check
      check (status in ('novo', 'chamado', 'proposta enviada', 'fechado', 'perdido'));
  end if;
end $$;

drop policy if exists leads_public_insert on public.leads;
create policy leads_public_insert
on public.leads
for insert
to anon, authenticated
with check (true);

drop policy if exists orcamentos_public_insert on public.orcamentos;
create policy orcamentos_public_insert
on public.orcamentos
for insert
to anon, authenticated
with check (true);

drop policy if exists contatos_public_insert on public.contatos;
create policy contatos_public_insert
on public.contatos
for insert
to anon, authenticated
with check (true);
